name: python-gh-output
description: testing writing output values in a python script

inputs:
  value:
    description: value for the output
    required: true

outputs:
  output-val:
    description: The output k/v pair based on input
    value: ${{ steps.write-value.outputs.value }}

runs:
  using: composite
  steps:
    - name: run python script
      shell: python
      id: write-value
      run: |
        import os

        value = "${{ inputs.value }}"

        with open(os.environ['GITHUB_OUTPUT'], 'a') as fh:
            print(f'value={value}', file=fh)
    - name: check output
      shell: bash
      run: echo "${{ steps.write-kv.outputs.value }}"
