name: Run actions
on: [push]
jobs:
  py-gh-output:
    runs-on: ubuntu-latest
    steps:
      - uses: dvmcconnell/gha-testing/actions/python-gh-output@main
        id: py-gh-output
        with:
          value: hey
      - run: |
          echo "${{ steps.py-gh-output.outputs.output-val }}"